export const configuration ={
	gallery:{
		images:[
			{img:'s1.webp',catg:'#heels'},
			{img:'s3.webp',catg:'#heels'},
			{img:'s4.webp',catg:'#flatshoes'},
			{img:'s5.webp',catg:'#sportshoes'},
			{img:'s6.webp',catg:'#redshoes'},
			{img:'s7.webp',catg:'#heels'},
			{img:'s8.webp',catg:'#sportshoes'},
			{img:'s9.webp',catg:'#sportshoes'},
			{img:'s10.webp',catg:'#flatshoes'},
			{img:'s11.webp',catg:'#heels'},
			{img:'s13.webp',catg:'#flatshoes'},
			{img:'s14.webp',catg:'#sportshoes'},
			{img:'s16.webp',catg:'#sportshoes'},
			{img:'s17.webp',catg:'#heels'},
			{img:'s18.webp',catg:'#sportshoes'},
			{img:'s21.webp',catg:'#shoes'},
			{img:'s19.jpg',catg:'#shoes'},
			{img:'s20.webp',catg:'#shoes'},
			{img:'s25.webp',catg:'#heels'},
			{img:'s28.webp',catg:'#flatshoes'},
			{img:'s29.jpg',catg:'#redshoes'},
			{img:'s30.jpg',catg:'#flatshoes'},
			{img:'s31.jpg',catg:'#redshoes'},
			{img:'s32.jpg',catg:'#flatshoes'},
			{img:'s33.webp',catg:'#redshoes'},
			{img:'s34.jpg',catg:'#flatshoes'},
			{img:'s35.webp',catg:'#heels'},
			{img:'s36.jpg',catg:'#flatshoes'}
		],
		sandals:[
		's1.webp',
		's3.webp',
		's10.webp',
		's22.webp',
		's36.jpg',
		's6.webp',
		's28.webp',
		's30.jpg',
		's7.webp',
		's32.jpg',
		's34.jpg',
		's11.webp',
		's15.jpg'
		]
	}

}